runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  static_files: dist/newproject/index.html
  upload: dist/newproject/index.html
- url: /
  static_dir: dist/newproject

skip_files:
- e2e/
- node_modules/
- src/
- ^(.*/)?\..*$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^LICENSE
