steps:

# Install node packages
- name: 'gcr.io/cloud-builders/npm@sha256:97cf9ccdca869e81c451259f7162139c4cf32d9181fb42fff1324c72bb00ca96'
  args: [ 'install' ]

# Build productive files
- name: 'gcr.io/cloud-builders/npm@sha256:97cf9ccdca869e81c451259f7162139c4cf32d9181fb42fff1324c72bb00ca96'
  args: [ 'run', 'build', '--prod' ]

# Deploy to google cloud app egnine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--version=prod']
