steps:

# Install node packages
- name: 'gcr.io/cloud-builders/npm@sha256:6d161bfa548fe5ea9c101ec5072b1c24d4ac7d9d88e2004d4d4101c82a13ec6c'
  args: [ 'install' ]

# Build productive files
- name: 'gcr.io/cloud-builders/npm@sha256:6d161bfa548fe5ea9c101ec5072b1c24d4ac7d9d88e2004d4d4101c82a13ec6c'
  args: [ 'run', 'build', '--prod' ]

# Deploy to google cloud app egnine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--version=prod']
