steps:

# Install node packages
- name: 'http://nodejs.org/download/release/latest-v12.x/node-v12.16.1.tar.gz'
  args: [ 'install' ]

# Build productive files
- name: 'https://nodejs.org/download/release/latest-v12.x/node-v12.16.1.tar.gz'
  args: [ 'run', 'build', '--prod' ]

# Deploy to google cloud app egnine
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--version=prod']
