runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  static_files: dist/helloworld/index.html
  upload: dist/helloworld/index.html
- url: /
  static_dir: dist/helloworld

skip_files:
- e2e/
- node_modules/
- src/
- ^(.*/)?\..*$
- ^(.*/)?.*\.json$
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.yaml$
- ^LICENSE
